# Generated by Django 5.2.4 on 2025-08-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoWebApp', '0004_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='icon',
            field=models.CharField(help_text='Font Awesome class (e.g., fas fa-music)', max_length=100),
        ),
    ]
