# Generated by Django 5.2.4 on 2025-08-04 12:48

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoWebApp', '0005_alter_event_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinistryCardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ministry Card Category',
                'verbose_name_plural': 'Ministry Card Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MinistryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='ministry_cards/')),
                ('age_group', models.CharField(blank=True, max_length=100)),
                ('meeting_time', models.CharField(blank=True, max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('button_text', models.CharField(default='Learn More', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='DjangoWebApp.ministrycardcategory')),
            ],
            options={
                'verbose_name': 'Ministry Card',
                'ordering': ['order'],
            },
        ),
    ]
