# Generated by Django 5.2.4 on 2025-08-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoWebApp', '0006_ministrycardcategory_ministrycard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ministrycard',
            options={'ordering': ['order'], 'verbose_name': 'Ministry Card In Ministry page'},
        ),
        migrations.AlterModelOptions(
            name='ministrycardcategory',
            options={'ordering': ['order'], 'verbose_name': 'Ministry Card Category In Ministries page', 'verbose_name_plural': 'Ministry Card Categories In Ministries Page'},
        ),
        migrations.AlterField(
            model_name='ministrycard',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
