# Generated by Django 5.2.4 on 2025-08-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoWebApp', '0009_sermonseries_speaker_sermon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('summary', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='series',
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='speaker',
        ),
        migrations.DeleteModel(
            name='SermonSeries',
        ),
        migrations.DeleteModel(
            name='Sermon',
        ),
        migrations.DeleteModel(
            name='Speaker',
        ),
    ]
