# Generated by Django 5.2.4 on 2025-08-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoWebApp', '0011_sermon_delete_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='sermons/audio'),
        ),
    ]
