# Generated by Django 5.2.4 on 2025-08-09 06:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoWebApp', '0014_alter_subscriber_options_alter_subscriber_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={},
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='subscribed_at',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', ckeditor.fields.RichTextField()),
                ('recipients', models.ManyToManyField(to='DjangoWebApp.subscriber')),
            ],
        ),
    ]
