# Generated by Django 5.2.4 on 2025-08-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoWebApp', '0015_alter_subscriber_options_remove_subscriber_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
